version: '3'

services:
  db:
    image: mysql:debian
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: tottoDB
    volumes:
      - ./mysql:/var/lib/mysql
