version: '3'

services:
  db:
    image: mysql:debian
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: doubleVDB
    volumes:
      - ./mysql:/var/lib/mysql
